"""Add relationship between Ticket and TicketMessage

Revision ID: f1580ac3abcc
Revises: ba3aed466ed1
Create Date: 2024-10-27 01:59:21.590426

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f1580ac3abcc'
down_revision: Union[str, None] = 'ba3aed466ed1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
