name: Backend CI/CD

on:
  push:
    branches: [ main ]
    paths:
      - 'backend/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'backend/**'
  workflow_dispatch:  # Allows manual triggering

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: ./backend
        file: ./backend/Dockerfile
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/suppercx-backend:latest

    - name: Verify push to DockerHub
      run: |
        echo "Attempting to pull the pushed image..."
        if docker pull ${{ secrets.DOCKERHUB_USERNAME }}/suppercx-backend:latest; then
          echo "Image successfully pushed and pulled from DockerHub"
        else
          echo "Failed to pull image from DockerHub. Push may have failed."
          exit 1
        fi
